export const CASE_STUDY_VISITORS = 100;
export const CASE_STUDY_A_SIGNUPS = 10;
export const CASE_STUDY_B_SIGNUPS = 11;
export const CASE_STUDY_A_RATE = CASE_STUDY_A_SIGNUPS / CASE_STUDY_VISITORS;
export const CASE_STUDY_B_RATE = CASE_STUDY_B_SIGNUPS / CASE_STUDY_VISITORS;
